# Generated by Django 4.1 on 2022-08-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=' ', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(max_length=150, unique=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='group',
            name='group_partner',
            field=models.CharField(db_index=True, default='Lagos', max_length=150),
        ),
    ]
