# Generated by Django 4.1 on 2022-08-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes', '0003_alter_customer_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='erp_no',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AddField(
            model_name='customer',
            name='ippis_no_oracle_no_staff_id',
            field=models.CharField(default=' ', max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.CharField(default=' ', max_length=10),
        ),
    ]
