# Generated by Django 4.1 on 2022-08-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthday_wishes', '0004_customer_erp_no_customer_ippis_no_oracle_no_staff_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='erp_no',
            field=models.IntegerField(default=' ', max_length=10),
        ),
    ]
